name: landslidenet
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - rasterio
  - matplotlib
  - shap
  - tqdm
  - joblib
  - jenkspy
  - catboost
  - lightgbm
